const schema = {
  calibration: {
    id: "string",
    number_of_freeze_dryers: "number",
    trays_per_machine_per_cycle: "number",
    cycle_time_hours: "number",
    defrost_cleaning_hours: "number",
    operating_hours_per_day: "number",
    operating_days_per_week: "number",
    fresh_load_per_tray_g: "number",
    dry_matter_fraction: "number",
    created_at: "string",
    user: { link: "users" },
  },
  microgreens: {
    id: "string",
    name: "string",
    soaking_required: "boolean",
    germination_days: "number",
    days_to_harvest: "number",
    sow_rate_g_per_tray: "number",
    notes: "string?",
    default_soak_offset_days: "number?",
    light_offset_days: "number?",
    harvest_offset_days: "number?",
    created_at: "string",
    user: { link: "users" },
  },
  yield_entries: {
    id: "string",
    microgreen: { link: "microgreens" },
    harvest_date: "string",
    fresh_yield_g: "number",
    dried_yield_g: "number?",
    tray_identifier: "string?",
    created_at: "string",
    user: { link: "users" },
  },
  inventory_items: {
    id: "string",
    name: "string",
    unit: "string",
    cost_per_unit: "number",
    quantity_on_hand: "number",
    par_level: "number?",
    last_count_date: "string?",
    created_at: "string",
    user: { link: "users" },
  },
  inventory_adjustments: {
    id: "string",
    inventory_item: { link: "inventory_items" },
    adjustment_type: "string",
    quantity_delta: "number",
    note: "string?",
    created_at: "string",
    user: { link: "users" },
  },
  products: {
    id: "string",
    name: "string",
    unit: "string",
    sale_price_per_unit: "number?",
    shelf_life_days: "number?",
    notes: "string?",
    is_microgreen: "boolean",
    microgreen: { link: "microgreens" },
    dried_needed_g_per_unit: "number",
    fresh_needed_g_per_unit: "number?",
    created_at: "string",
    user: { link: "users" },
  },
  bom_lines: {
    id: "string",
    product: { link: "products" },
    inventory_item: { link: "inventory_items" },
    qty_per_unit: "number",
    unit_label: "string",
    user: { link: "users" },
  },
  production_cycles: {
    id: "string",
    start_date: "string",
    end_date: "string",
    status: "string",
    business_type: "string",
    harvest_date: "string?",
    created_at: "string",
    user: { link: "users" },
  },
  product_variants: {
    id: "string",
    product: { link: "products" },
    name: "string",
    size_oz: "number",
    sku: "string?",
    sale_price: "number?",
    unit_cost: "number?",
    is_active: "boolean",
    created_at: "string",
    user: { link: "users" },
  },
  production_targets: {
    id: "string",
    production_cycle: { link: "production_cycles" },
    product: { link: "products" },
    target_units: "number",
    product_variant_id: "string?",
    quantity_to_produce: "number?",
    extra_full_trays: "number?",
    user: { link: "users" },
  },
  production_plan_lines: {
    id: "string",
    production_cycle: { link: "production_cycles" },
    microgreen: { link: "microgreens" },
    source_product: { link: "products" },
    business_type: "string?",
    product_variant_id: "string?",
    fresh_required_g: "number",
    run_number: "number",
    trays_this_run: "number",
    soak_date: "string?",
    drain_date: "string?",
    sow_date: "string",
    light_date: "string",
    harvest_date: "string",
    user: { link: "users" },
  },
  users: {
    id: "string",
    email: "string?",
  },
};

export default schema;

